services:
  postgres:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2019!"
    ports:
      - "5432:5432"
    volumes:
      - /Documentos/BasesDeDados/compose-pgadmin/PostgreSQL:/var/lib/postgresql/data 
    networks:
      - postgres-network
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "leocampos8787@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge